title: Binglin Hao's Academic Homepage
page-top-title: Binglin Hao's Academic Homepage
top-section-bg-text: Build on the shoulders of giants
home-subtitle: Binglin Hao&ensp;|&ensp;Wuhan University
copyright-text: "&copy; Binglin Hao 2023-2025. All Rights Reserved."
